CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DROP TABLE APPLICATION_USER;

CREATE TABLE IF NOT EXISTS APPLICATION_USER(
    UUID       UUID         DEFAULT UUID_GENERATE_V4(),
    USERNAME   VARCHAR      UNIQUE NOT NULL,
    PASSWORD   VARCHAR      NOT NULL,
    EMAIL      VARCHAR(255) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,   
    PRIMARY KEY (UUID)
);

SET TIMEZONE TO 'America/Sao_Paulo';

INSERT INTO APPLICATION_USER (USERNAME, PASSWORD, EMAIL) VALUES ('admin', crypt('admin', 'my_salt'), 'admin@email.com');
INSERT INTO APPLICATION_USER (USERNAME, PASSWORD, EMAIL) VALUES ('teste', crypt('teste', 'my_salt'), 'teste@email.com');

SELECT * FROM APPLICATION_USER;