CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DROP TABLE APPLICATION_USER;

CREATE TABLE IF NOT EXISTS APPLICATION_USER(
    UUID       UUID         DEFAULT UUID_GENERATE_V4(),
    USERNAME   VARCHAR      UNIQUE NOT NULL,
    PASSWORD   VARCHAR      NOT NULL,
    EMAIL      VARCHAR(255) UNIQUE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,   
    PRIMARY KEY (UUID)
);

SET TIMEZONE TO 'America/Sao_Paulo';

INSERT INTO APPLICATION_USER (USERNAME, PASSWORD, EMAIL) VALUES ('admin', crypt('admin', 'my_salt'), 'admin@email.com');
INSERT INTO APPLICATION_USER (USERNAME, PASSWORD, EMAIL) VALUES ('teste', crypt('teste', 'my_salt'), 'teste@email.com');

DROP TABLE REFRESH_TOKEN;
CREATE TABLE IF NOT EXISTS REFRESH_TOKEN (
    ID         UUID    DEFAULT UUID_GENERATE_V4(),
    UUID       UUID    NOT NULL,
    USERNAME   VARCHAR NOT NULL,
    EXPIRESIN  INT     NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK_APPLICATION_USER
        FOREIGN KEY(UUID) 
        REFERENCES APPLICATION_USER(UUID)
);

INSERT INTO REFRESH_TOKEN (UUID, EXPIRESIN) VALUES ('03ecfd41-a9ea-4155-8d27-e51c73ad3256', 1);